language: python
python:
  - "3.6"
  - "3.7-dev"
# command to install dependencies
install:
  - pip3 install -r requirements.txt
  - pip3 install coveralls
# command to run tests
script:
  - python -m pytest --cov=app/tests
after_success:
- coveralls